CONFIG_ESP32_ULP_COPROC_ENABLED=y
CONFIG_ESP32_ULP_LP_CORE_WAKEUP_SOURCE_LP_TIMER=y
CONFIG_ESP32_ULP_LP_CORE_LP_TIMER_SLEEP_DURATION_US=30000000

CONFIG_POWEROFF=y
CONFIG_HWINFO=y
CONFIG_MBOX=y

#CONFIG_LPS_EXPLICIT_LP_IMAGE_LOADING=y
#CONFIG_LPS_USE_LIGHT_SLEEP=y

# Probably want to configure these things together (the main reason
# to "always stay awake" is so that the shell doesn't disappear).
CONFIG_LPS_HPCORE_ALWAYS_STAY_AWAKE=n
CONFIG_NET_SHELL=n
CONFIG_NET_L2_WIFI_SHELL=n


# WiFi/Network stuff

# --- Wi-Fi & Networking ---
CONFIG_WIFI_ESP32=y
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_WIFI=y
CONFIG_REBOOT=y

# --- MQTT Library ---
CONFIG_MQTT_LIB=y
CONFIG_MQTT_CLEAN_SESSION=y

# --- Memory Tuning (Networking requires more RAM) ---
CONFIG_HEAP_MEM_POOL_SIZE=81920
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# --- Hardcoded Wi-Fi Credentials (for testing) ---
CONFIG_WIFI_CREDENTIALS=y
CONFIG_WIFI_CREDENTIALS_STATIC=y
CONFIG_WIFI_CREDENTIALS_STATIC_SSID="YourSSID"
CONFIG_WIFI_CREDENTIALS_STATIC_PASSWORD="YourPSK"

#CONFIG_NET_DHCPV4=y
CONFIG_LPS_IP_ADDR="192.168.1.55"
CONFIG_LPS_GW="192.168.1.1"
CONFIG_LPS_NETMASK="255.255.255.0"

CONFIG_LPS_MQTT_BROKER_ADDR="192.168.1.3"
CONFIG_LPS_MQTT_BROKER_PORT=1883
CONFIG_LPS_MQTT_BROKER_USERNAME="sensor_user"
CONFIG_LPS_MQTT_BROKER_PASSWORD="$en$or_pa$$word"


