# Choose one of these two options
CONFIG_LPS_TRANSPORT_WIFI_MQTT=y

# --- Hardcoded Wi-Fi Credentials (for testing) ---
CONFIG_WIFI_CREDENTIALS=y
CONFIG_WIFI_CREDENTIALS_STATIC=y
CONFIG_WIFI_CREDENTIALS_STATIC_SSID="<your ssid>"
CONFIG_WIFI_CREDENTIALS_STATIC_PASSWORD="<your psk>"

CONFIG_LPS_DHCP_CLIENT=y
# Note static network config only used if CONFIG_LPS_DHCP_CLIENT=n
CONFIG_LPS_IP_ADDR="192.168.1.55"
CONFIG_LPS_GW="192.168.1.1"
CONFIG_LPS_NETMASK="255.255.255.0"

CONFIG_LPS_MQTT_BROKER_ADDR="192.168.1.3"
CONFIG_LPS_MQTT_BROKER_PORT=1883
CONFIG_LPS_MQTT_BROKER_USERNAME="sensor_user"
CONFIG_LPS_MQTT_BROKER_PASSWORD="$en$or_pa$$word"


