# Enable Zephyr Logging
CONFIG_LOG=y

# 0-4  4 is DEBUG
CONFIG_LPS_LOG_LEVEL=0


# nothing here
CONFIG_MBOX=y

# Minimal logging mode might be required for the LP core to stay under 8KB
CONFIG_LOG_MODE_MINIMAL=y
